### ISSUE TITLE
远程服务器返回错误

### ISSUE THREAD

**Issue by znonousy** [EveElseIf/BiliDownloadUWP#2]
the remote server returned an error :(412) Precondition Failed. 
下午下载了阿b一些多p的视频完成后，无法继续下载，弹窗报错。重启重新登录改路径都没用

**Comment by EveElseIf** [comment]
这个报错其实是因为b站返回了412码，意思大概是因为非法操作而被暂时封禁（参见http status code 412），可能是因为对服务器的频繁请求造成的。解决办法是等一段时间再用，或者换一个IP地址。
